### ISSUE TITLE
Create more grading models

### ISSUE THREAD

**Issue by afokou** [dnna/pixelbonus#19]
Grading models to create:
- Raw
- Mins adjusted (fitted)
- Max adjusted (range fitted)

**Comment by dnna** [comment]
This is now complete. The changes were as follows:
1. Added grading models Curved Grading and Ranking. They can be selected through the user profile. Curved Grading allows a "grade multiplier", "max grade" and "min grade" parameters. If ranking is selected the parameters are ignored.
2. Removed the existing "regression" model, as it was calculating grades in a wrong way.
3. Added ASC and DESC sorting for the grades table. An arrow in the column header link now indicates whether the column is ascending or descending.

Also created task #40 to add tooltip in user profile to make grading models and parameters more understandable.
