### ISSUE TITLE
Activity overview page

### ISSUE THREAD

**Issue by dspinellis** [dnna/pixelbonus#28]
I'd like to have a page where the bonus points of all participants of an activity can be seen.  Ideally it should have an opaque URL, e.g. pixelbonus.com/activity/754d84e375832ee476f52aa37465293dc8b7f4ed563ba4

**Comment by dnna** [comment]
I'm not sure if I understand this correctly. Are we talking about a public page that contains a table with columns student identifier, redemption counts and grade (akin to the grades page but without requiring login)? Or is the page more about showing summarized stats?

**Comment by dspinellis** [comment]
Yes, a public page that contains a table with columns student identifier, redemption counts and grade like [this one](http://www.dmst.aueb.gr/dds/isdi/exercise/part.htm).  Ideally the page should have a somewhat opaque URL, but this is not terribly important.

**Comment by dnna** [comment]
This page is ready. There is a link for it in the main activity page that can be given out to the participants.
