### ISSUE TITLE
Long bottom margins and a small offset in the first page

### ISSUE THREAD

**Issue by dspinellis** [dnna/pixelbonus#32]
Following #27 the situation is markedly improved.  Two problems remain:
- [x] On pp. 1-13 of the attached the bottom margin is very long.  At least one more QR code row could fit there.
- [x] Page 1 is slightly vertically offset than the rest. (This is visible in full page view.)  This creates a problem when cutting the pages in batches.

[qr.pdf](https://github.com/dnna/pixelbonus/files/148851/qr.pdf)

**Comment by dnna** [comment]
All alignment issues should be fixed now. We also manged to fit 2 extra QR code rows per page by slightly reducing the top/bottom margin of all pages.

**Comment by dspinellis** [comment]
Excellent!  If all goes well will start using it on Monday's lecture.
