### ISSUE TITLE
Include "pixelbonus.com" in the printed CQS codes

### ISSUE THREAD

**Issue by dspinellis** [dnna/pixelbonus#35]
No need for a full URL; humans and browsers know what to do with it.

**Comment by dnna** [comment]
Do you mean change the URL the QR code leads to to pixelbonus.com/redeem?hash=752af80475388d1cebf046557ce10667620f7fba (basically the same as now but without the http:// part)?

Or do you mean add pixelbonus.com in plain text somewhere inside the QR code box so people know where to redeem it if they can't scan the code?

**Comment by dspinellis** [comment]
Yes, add `pixelbonus.com` in plain text under the hexadecimal code, so people know where to redeem it if they can't scan the code.  This will also promote the system's brand.

**Comment by dnna** [comment]
Its done
