### ISSUE TITLE
Ask for confirmation when deleting activities and sets

### ISSUE THREAD

**Issue by dspinellis** [dnna/pixelbonus#37]
This could be done with a JavaScript popup.

**Comment by dnna** [comment]
There are already popups for this. Please check the screenshot.
![popups](https://cloud.githubusercontent.com/assets/1296821/13465747/a04053e6-e09f-11e5-9444-dc1ea7b1bba2.png)

**Comment by dspinellis** [comment]
I guess I clicked through :-).

**Comment by dnna** [comment]
I'll change them to a prompt requiring the user to type YES so its a little harder to do this.

**Comment by dspinellis** [comment]
:+1:
