### ISSUE TITLE
Server error 500 when I ordered 400 tokens

### ISSUE THREAD

**Issue by dspinellis** [dnna/pixelbonus#38]
I suggest that the generation of tokens should be asynchronous. Organizers should be directed to page, which gets periodically refreshed until the tokens have been generated.  Alternatively, they can get an email.

**Comment by dnna** [comment]
QR code generation has now been implemented to be asynchronous. After the user clicks to generate codes the system will prepare them in the background and send an email with a link to download them once they are ready.
